#!/bin/bash
basedir=`dirname "$0"`

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  "$basedir/node"  "./platypus-docs/plat-docs.js" "$@"
  ret=$?
else 
  node  "./platypus-docs/plat-docs.js" "$@"
  ret=$?
fi
exit $ret
